# Generated by Django 3.0.6 on 2020-05-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200525_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='匿名', max_length=128),
        ),
    ]
